### ISSUE TITLE
Error focussing browserwindow

### ISSUE THREAD

**Issue by nsuedkamp** [sachatholl/Orbitron2WebSDR#1] opened 2023-06-04 11:12 UTC
When Radio Automatic Mode is enabled, the Program changes the frequency exactly one, before giving an error stating that there is an issue focussing the browser window. This is shown in the video i attached. What isn't shown there is that the buttons to change from USB to CW/FM/AM/... doesn't work either.

https://github.com/sachatholl/Orbitron2WebSDR/assets/135513422/d2a86ef0-bf18-4978-a3ab-3380d4c86589

**Comment by sachatholl** [comment] 2023-06-04 11:31
Dear nsuedkamp , 
Thank you for your report. I will check the issue and provide an update asap. 
Cheers,
Sash

**Comment by sachatholl** [comment] 2023-06-04 23:27
Okay, I can confirm the issue. Although it updates the frequency one time, in the next step of the loop, the app can no longer find the correct browser window. Since I am looking up the tasklist in the task manager against the window labels, I will check if the label of the newer version of Firefox dynamically changes, such that the app cannot perform a correct comparison, since in the browser tab, recently one can readout information like "playing", stopped, etc... I will check and try to fix soon.

![image](https://github.com/sachatholl/Orbitron2WebSDR/assets/3606905/e165e6e3-bd60-40fc-9de5-f3dd58c3f06a)

**Comment by sachatholl** [comment] 2023-06-09 23:57
Found the issue. Works with vi, but not after compiling—uploaded fix for Doppler correction. Now the Doppler correction works again, imediatly after you Focus to the WebSDR Window by a mouse click.

But to get the automatic focus to work, try this:  reengaging twice (engage, disengage, and reengage again). 

The new version then finds the WebSDR window focus and radio mode buttons work again. I will continue working on a 100% fix. A temporary fix is in place, and at least the Doppler correction on WebSDR is working again.

I performed the test using Chrome browser. Can you try using Firefox?

Cheers,
Sash

**Comment by sachatholl** [comment] 2023-07-24 16:01
New Version uploaded, dopler correction issue has been fixed

**Closed as completed by sachatholl** 2023-07-24 16:01 UTC
